[tool.poetry]
name = "daml"
version = "0.0.1"
description = "DAML provides a simple interface to characterize image data and its impact on model performance across classification and object-detection tasks"
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.jatic.net/jatic/aria/daml"
repository = "https://gitlab.jatic.net/jatic/aria/daml"

authors = [
  "James Gleeson <james.gleeson@ariacoustics.com>",
  "Shaun Jullens <shaun.jullens@ariacoustics.com>",
  "Andrew Weng <andrew.weng@ariacoustics.com>",
]

classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering",
  "Programming Language :: Python :: 3 :: Only",
]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
