[tool.poetry]
name = "daml"
version = "0" # dynamic
description = "DAML provides a simple interface to characterize image data and its impact on model performance across classification and object-detection tasks"
license = "MIT"
readme = "README.md"
homepage = "https://jatic.pages.jatic.net/aria/daml/"
repository = "https://gitlab.jatic.net/jatic/aria/daml/"

authors = ["ARiA <daml@ariacoustics.com>"]
maintainers = [
  "Andrew Weng <andrew.weng@ariacoustics.com>",
  "James Gleeson <james.gleeson@ariacoustics.com>",
  "Jason Inman <jason.inman@ariacoustics.com>",
]

classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering",
  "Programming Language :: Python :: 3 :: Only",
]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
numpy = "1.24.3"
nvidia-cudnn-cu11 = {version = "8.6.0.163"}
opencv-contrib-python-headless = {version = "4.8.0.76"}
scipy = "*"
scikit-learn = "*"
torch = {version = "*", source = "pytorch"}
torchvision = {version = "*", source = "pytorch"}
torchmetrics = {version = "*", source = "pytorch"}
alibi-detect = {version = "0.11.4", extras = ["tensorflow"], optional = true}
tensorflow = {version = "2.12.1", optional = true}

[tool.poetry.extras]
alibi-detect = ["alibi-detect", "tensorflow"]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
# test
pytest = "*"
coverage = "*"
# type
pyright = "1.1.331"
# lint
flake8 = "*"
flake8-pyproject = "*"
black = { extras = ["jupyter"], version = "*" }
isort = "*"
codespell = "*"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
ipykernel = "6.25.2"
ipywidgets = "8.1.1"
nbsphinx = "0.9.3"
sphinx-rtd-size = "0.2.0"
sphinx-rtd-theme = "1.3.0"
Sphinx = "7.1.2"
tensorflow-datasets = "*"

[tool.poetry.group.jatic]
optional = true

[tool.poetry.group.jatic.dependencies]
jatic-toolbox = {version = "*", source = "jatic"}

[[tool.poetry.source]]
name = "jatic"
url = "https://gitlab.jatic.net/api/v4/groups/101/-/packages/pypi/simple"
priority = "explicit"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.pyright]
reportMissingImports = false

[tool.pytest.ini_options]
markers = [
  "functional: marks slower functional tests",
]

[tool.black]
extend-exclude = '\.tox|.*env.*|docs|output\/'

[tool.isort]
profile = 'black'
skip_glob = [
    ".tox",
    "*env*",
    "docs/*",
    "output/*"
    ]

[tool.flake8]
count = true
exclude = [
    ".tox",
    "*env*",
    "docs/*",
    "output/*"
    ]
max-line-length = 88

[tool.codespell]
skip = '*env*,./docs/_build,CHANGELOG.md,poetry.lock,output'

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
