[build-system]
requires = ["setuptools>=59.6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "daml"
version = "0.0.1"
description = "DAML provides a simple interface to characterize image data and its impact on model performance across classification and object-detection tasks"
readme = "README.md"
require-python = ">=3.8"

authors = [
    {name = "James Gleeson", email = "james.gleeson@ariacoustics.com" },
    {name = "Shaun Jullens", email = "shaun.jullens@ariacoustics.com" },
    {name = "Andrew Weng", email = "andrew.weng@ariacoustics.com" }
]

classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Scientific/Engineering",
  "Programming Language :: Python :: 3 :: Only",
]

[project.urls]
"Homepage" = "https://gitlab.jatic.net/jatic/aria/daml"
"Bug Reports" = "https://gitlab.jatic.net/jatic/aria/daml/-/issues"
"Source" = "https://gitlab.jatic.net/jatic/aria/daml"
