[tool.poetry]
name = "daml"
version = "0" # dynamic
description = "DAML provides a simple interface to characterize image data and its impact on model performance across classification and object-detection tasks"
license = "MIT"
readme = "README.md"
homepage = "https://jatic.pages.jatic.net/aria/daml/"
repository = "https://gitlab.jatic.net/jatic/aria/daml/"

authors = ["ARiA <daml@ariacoustics.com>"]
maintainers = [
  "Andrew Weng <andrew.weng@ariacoustics.com>",
  "James Gleeson <james.gleeson@ariacoustics.com>",
  "Jason Inman <jason.inman@ariacoustics.com>",
]

classifiers = [
  "Development Status :: 4 - Beta",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Topic :: Scientific/Engineering",
  "Programming Language :: Python :: 3 :: Only",
]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
numpy = ">=1.24.2"
nvidia-cudnn-cu11 = {version = "8.6.0.163"}
scipy = {version = ">=1.10" }
scikit-learn = {version = ">=1.2.1" }
torch = {version = ">=2.1.0", source = "pytorch"}
torchvision = {version = ">=0.16.0", source = "pytorch"}
torchmetrics = {version = ">=1.0.0", source = "pytorch"}
alibi-detect = {git = "https://github.com/SeldonIO/alibi-detect.git", rev = "7dcac8a", extras = ["tensorflow"], optional = true}
tensorflow = [
  {version = "~2.13.1", python = "~3.8.1", optional = true},
  {version = "~2.14.1", python = ">=3.9,<3.12", optional = true},
]
tensorflow_probability = [
  {version = "~0.21.0", python = "~3.8.1", optional = true},
  {version = "~0.22.1", python = ">=3.9,<3.12", optional = true},
]

[tool.poetry.extras]
alibi-detect = ["alibi-detect", "tensorflow", "tensorflow_probability"]

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
# test
pytest = "*"
coverage = "*"
# type
pyright = {version = "*, !=1.1.340"}
# lint
flake8 = "*"
flake8-pyproject = "*"
black = { extras = ["jupyter"], version = "*" }
isort = "*"
codespell = "*"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
ipykernel = {version = "6.26.0", python = ">=3.9,<3.12"}
ipywidgets = {version = "8.1.1", python = ">=3.9,<3.12"}
jupyter-client = {version = "8.6.0", python = ">=3.9,<3.12"}
myst-nb = {version = "1.0.0", python = ">=3.9,<3.12"} 
sphinx-rtd-size = {version = "0.2.0", python = ">=3.9,<3.12"}
sphinx-rtd-theme = {version = "1.3.0", python = ">=3.9,<3.12"}
Sphinx = {version = "7.2.6", python = ">=3.9,<3.12"}
tensorflow-datasets = {version = "*", python = ">=3.9,<3.12"}

[tool.poetry.group.jatic]
optional = true

[tool.poetry.group.jatic.dependencies]
maite = {version = "*", source = "jatic"}

[[tool.poetry.source]]
name = "jatic"
url = "https://gitlab.jatic.net/api/v4/groups/101/-/packages/pypi/simple"
priority = "explicit"

[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.pyright]
reportMissingImports = false

[tool.pytest.ini_options]
markers = [
  "interop: marks external library interop tests",
  "functional: marks slower functional tests",
]

[tool.black]
extend-exclude = '\.tox|.*env.*|docs|output\/'

[tool.isort]
profile = 'black'
skip_glob = [
    ".tox",
    "*env*",
    "docs/*",
    "output/*"
    ]

[tool.flake8]
count = true
exclude = [
    ".tox",
    "*env*",
    "docs/*",
    "output/*"
    ]
max-line-length = 88

[tool.codespell]
skip = '*env*,./docs/_build,CHANGELOG.md,poetry.lock,output'

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
