workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule' || $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main'
      variables:
        BUILD: "build"

.build:
  stage: build
  rules:
    - if: $BUILD

.build_docker:
  extends: .build
  image: docker:24.0-git
  before_script:
    - if [[ ! $(which bash) ]]; then apk add --no-cache bash; fi
    - echo ${DAML_HARBOR_TOKEN} | docker login harbor.jatic.net:443 -u 'robot$daml+daml-build' --password-stdin
  after_script:
    - docker logout harbor.jatic.net:443
  allow_failure: true

verify lock:
  extends: .build
  before_script:
    - pip install poetry
  script:
    - poetry check
  rules:
    - if: $BUILD

build base:
  extends: .build_docker
  script:
    - ./build --build-only --push --verbose base

build image:
  extends: .build_docker
  needs: [verify lock, build base]
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.8", "3.9", "3.10", "3.11"]
  script:
    - ./build --build-only --push --verbose ${PYTHON_VERSION}
