.publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' 

# This job should only run if all the "needs" have succeeded,
# and it creates a tag that signifies that all testing has passed.
tag release candidate:
  extends: .publish
  environment:
    name: production
  needs: [docs, linting, dependency tests, functional tests]
  script:
    - pip install requests
    - .gitlab/update_latest_known_good.py

pages:
  extends: .publish
  needs:
    - job: docs
      artifacts: true
    - job: coverage
      artifacts: true
  script:
    - mv output/docs/html/ ./public/
    - mv htmlcov/ ./public/coverage/
  artifacts:
    paths:
      - public
