include:
  - template: Security/Secret-Detection.gitlab-ci.yml
#  - template: Security/Dependency-Scanning.gitlab-ci.yml
#  - template: Security/SAST.gitlab-ci.yml

secret_detection:
  stage: security
  needs: []
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'

# generate shipped dependencies:
#   stage: security
#   before_script:
#     - pip install poetry
#     - poetry check
#     - poetry self add poetry-lock-groups-plugin
#   script:
#     - poetry lock --without test,lint,docs
#   artifacts:
#     paths:
#       - poetry.lock
#   rules:
#     - if: $CI_COMMIT_REF_PROTECTED == "true"
#     - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'

# gemnasium-python-dependency_scanning:
#   stage: security
#   needs:
#     - job: generate shipped dependencies
#       artifacts: true
#   # Both `needs` and `dependencies` are used due to a quirk of gitlab.
#   # `gemnasium-python-dependency_scanning` specifies an empty list of
#   # dependencies, which means that unless you explicitly add the dependency,
#   # all artifacts will be filtered out and removed from this job.
#   dependencies:
#     - generate shipped dependencies
#   rules:
#     - if: $CI_COMMIT_REF_PROTECTED == "true"
#     - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'

# semgrep-sast:
#   stage: security
#   needs: []
#   rules:
#     - if: $CI_COMMIT_REF_PROTECTED == "true"
#     - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
